//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExcelFile
    {
        public int ExcelId { get; set; }
        public string NameFile { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public System.DateTime UploadTime { get; set; }
        public int UserId { get; set; }
        public string Employee { get; set; }
    
        public virtual ExcelFile ExcelFile1 { get; set; }
        public virtual ExcelFile ExcelFile2 { get; set; }
    }
}
