//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExcelData
    {
        public int DataId { get; set; }
        public Nullable<int> ExcelId { get; set; }
        public Nullable<int> No { get; set; }
        public string Crossdock { get; set; }
        public string ProductName { get; set; }
        public string PO_NO { get; set; }
        public string InvoiceNo { get; set; }
        public string APC_Order { get; set; }
        public string DeliverId { get; set; }
        public string StoreId { get; set; }
        public string DateTime { get; set; }
        public string Province { get; set; }
        public string District { get; set; }
        public string StoreName { get; set; }
        public string ProductId { get; set; }
        public string ProductDetail { get; set; }
        public Nullable<int> Box { get; set; }
        public Nullable<int> Piece { get; set; }
        public Nullable<decimal> CBM { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string Category { get; set; }
        public string Note { get; set; }
        public string Week { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual ExcelData ExcelData1 { get; set; }
        public virtual ExcelData ExcelData2 { get; set; }
    }
}
