//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExclusiveCompany
    {
        public int ExclusiveId { get; set; }
        public string Company { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ExclusiveCompany ExclusiveCompany1 { get; set; }
        public virtual ExclusiveCompany ExclusiveCompany2 { get; set; }
    }
}
