//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistic.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class masterEntities : DbContext
    {
        public masterEntities()
            : base("name=masterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Districts> Districts { get; set; }
        public virtual DbSet<ExcelData> ExcelData { get; set; }
        public virtual DbSet<ExcelFile> ExcelFile { get; set; }
        public virtual DbSet<ExclusiveCompany> ExclusiveCompany { get; set; }
        public virtual DbSet<Item> Item { get; set; }
        public virtual DbSet<Provinces> Provinces { get; set; }
        public virtual DbSet<RatePrice> RatePrice { get; set; }
        public virtual DbSet<Subdistricts> Subdistricts { get; set; }
        public virtual DbSet<UserProfile> UserProfile { get; set; }
    }
}
